### PR TITLE
add explanation for :55 precedence

### PR DESCRIPTION
**Pull request by yunjiangster**
Thanks to Bryan Gin-ge Chen for the explanation.

### CODE REVIEW

**Comment by PatrickMassot** [comment]
I'm not convinced this is understandable for anyone who doesn't already know this. A better solution may be to simply remove this notation. 

Note: any modification needs to be done also to the solution file. The recommended workflow is to fix the solution file and then run the script that build the exercises.

**Comment by yunjiangster** [comment]
> I'm not convinced this is understandable for anyone who doesn't already know this. A better solution may be to simply remove this notation.
> 
> Note: any modification needs to be done also to the solution file. The recommended workflow is to fix the solution file and then run the script that build the exercises.

Done. Let me know of other recommendations.

**Comment by PatrickMassot** [comment]
I'm sorry but I don't understand what you've done. Does your version work? And you kept your sentence about this 55 while removing the 55. This is completely inconsistent and I don't see how it could compile.

**Comment by yunjiangster** [comment]
> I'm sorry but I don't understand what you've done. Does your version work? And you kept your sentence about this 55 while removing the 55. This is completely inconsistent and I don't see how it could compile.

Thank you for careful review. I indeed forgot to remove my earlier added comments, which should have been removed in the latest patch. I also compiled the project using lean without any problem. Let me know if you see other issues. 

`lean src/exercises/00_first_proofs.lean`

> upper_bounds : set ?M_1 → set ?M_1
> Try this: exact one_div_pos.mpr this
> Try this: exact le_abs_self (u N - x)

**Comment by yunjiangster** [comment]
> I'm sorry but I don't understand what you've done. Does your version work? And you kept your sentence about this 55 while removing the 55. This is completely inconsistent and I don't see how it could compile.

Thanks for careful reviewing. Indeed I forgot to remove my earlier added comment. Now I tried removing :55 precedence annotation but lean complains about lack of type. 

> /Users/yunjiang.jiang/dev/tutorials/src/exercises/00_first_proofs.lean:49:6: error: invalid notation declaration, precedence was not provided, and it is not set for the given symbol, solution: use the 'precedence' command

So perhaps I should revert to the first version? I for one understood it much better after knowing it stood for precedence.

**Comment by MasterJames** [comment]
This without the comment confused me greatly too. Still I am left wondering why "55"? is it just like a number that is greater then whatever is_maximum is currently ENUMerated to in a list of the compiler? Clearly the comment is needed but maybe it could include a deeper reading via a link to a document explaining why the number 55? is it the line number in the file? totally lost here (being new to it, yes. first file 00_first_proofs, yes. so it should be explained more then 'precedence'?.) Oh or it's 55 is a function or type called 'precedence'? I got only hopeless random guesses here. maybe there is a better way to declare it has precedence like ":precedence" instead of ":55". Again the comment is needed, but it's really not enough for Noobs.

**Pull request closed without merging**
