### PR TITLE
Fix typo in 04_exists.lean

### PR DESCRIPTION
**Pull request by DanielFabian**

### CODE REVIEW

**Comment by PatrickMassot** [comment]
Thanks! Could you please edit the solutions files and run `mk_exercises.py` (or simply keep your edit). The exercises are automatically generated from the solutions files, not the other around (I don't what all those AI people are doing...).

**Comment by DanielFabian** [comment]
of course, I will. So far, I wasn't doing that, because I didn't fork the repo yet. Gimme a few days, please as I'm working through the tutorial.

**Comment by PatrickMassot** [comment]
Also beware that Dan is also fixing typos, so you should make sure to git pull before working on a patch.

**Comment by DanielFabian** [comment]
will do.

**Comment by DanielFabian** [comment]
Closing, because the fixes are already there.

**Comment by PatrickMassot** [comment]
Thanks anyway!

**Pull request closed without merging**
